export const LOGIN_REQUEST = "AUTH/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "AUTH/LOGIN_FAILURE";
export const LOGOUT = "AUTH/LOGOUT";

export const FORGOT_PASSWORD_REQUEST = "AUTH/FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "AUTH/FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "AUTH/FORGOT_PASSWORD_FAILURE";

export const UPDATE_PASSWORD_REQUEST = "AUTH/UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "AUTH/UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "AUTH/UPDATE_PASSWORD_FAILURE";

export const UPDATE_PROFILE_REQUEST = "AUTH/UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "AUTH/UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "AUTH/UPDATE_PROFILE_FAILURE";
